---
output: 
  html_document:
    css: custom.css
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
```

<div class='jumbotron'>
  <h2 class='display-3 text-uppercase'>Assignment 7</h2>
  <h4 class='right text-uppercase'>By Brian Weinfeld</h4>
  <div class='clearfix'></div>
  <h5 class='right text-uppercase'>April 16th, 2018</h5>
</div>

<div class='page-header text-uppercase'>
  <h3>Recommender Systems</h3>
</div>

<div class='alert alert-success'>
I decided to examine the recommender system at [What Should I Read Next?](http://www.whatshouldireadnext.com/). As the name implies this site allows you to type in books you enjoyed to find suggestions on other similar books.
</div>

<div class='well'>

1. Perform a Scenario Design analysis as described below.  Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.
</div>

<div class='well'>
Scenario Design:

1. The target users are readers who are interested in a more personal touch in their reading recommendations. These users more heavily regard the recommendations of other readers over the recommendations of sites like Amazon designed to promote and sell popular, in stock books.

2. Ther user's key goal is to find books they may find enjoyable that fall under specific categorizations. 

3. The site aids them in this goal by using a recommendor system to promote books that may be appropriate matches. Unlike sales sites though, the books are recommended based on being placed on specific lists by the sites other users.
</div>

<div class='well'>

2. Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.
</div>

<div class='well'>
Based on exploration of the site, I've discovered a useful, if basic, recommendor system. Readers register for the site and create lists of their favorite books, categorizing them based on related traits. These books become bound together in the site's database and the more users that link these books, the higher the likelyhood that book will be shown to other users who type in similar books.

This system aims to improve on sites like Amazon by being able to create lists of favorites based on criteria. For example, perhaps I enjoy both Science Fiction and Data Science books. Although I may rate books in both categories highly, there is no reason to recommend Data Science books to other users looking for Science Fiction.

The site's FAQ indicates that they use a 'collaborative filtering system using our own bespoke algorithm called "Incidence Bias Weighting"'.
</div>

<div class='well'>

3. Include specific recommendations about how to improve the site's recommendation capabilities going forward. 
</div>

<div class='well'>
Part of the reason I found the site to work so well was specifically because it was not trying to perform any complicated advanced analysis. It almost seems antithetical to the nature of the site to suggest complicated improvements.

With that being said, I think it would be benficial to implement a system that provides additional weighting to verified purchasers. After you discover a book, the sites provides an affiliate link to Amazon so that it may be purchased. This is done to help keep the site running but it could also be used to improve recommendations.

Did a user buy a book through the affiliate link? Then perhaps they thought highly of the recommendation. 

Did they later positively rate it on the site? Then this is a perfect recommendation! Negatively? Then this may be a misclassification.

This has the downside of providing additional influence to users who spend money (and support the site) but it is clear from the design of the site that they are small enough to not really worry about arbitrage. 
</div>